version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    command: redis-cli --raw ACL SETUSER john on >123pass +@all ~*
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"